presubmits:
  - name: test-needs-retitle
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/needs-retitle.git"
    max_concurrency: 1
    trigger: "(?m)test( please)?"
    rerun_command: "test"
    spec:
      containers:
        - name: "test"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/go-builder:1.14.2
          command:
            - make
          args:
            - test
  - name: bleh
    decorate: true
    labels:
      preset-semantic-release: "true"
      preset-gcloud-testinfra-prow: "true"
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/needs-retitle.git"
    max_concurrency: 1
    trigger: "(?m)bleh( please)?"
    rerun_command: "bleh"
    spec:
      containers:
        - name: "bleh"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/go-builder:1.14.2
          command:
            - make
          args:
            - init-gcloud-cli
            - gcloud-docker-build
postsubmits:
  - name: needs-retitle-release
    labels:
      preset-semantic-release: "true"
      preset-gcloud-testinfra-prow: "true"
    clone_uri: "git@github.com:ouzi-dev/needs-retitle.git"
    decorate: true
    max_concurrency: 1
    branches:
      - master
    spec:
      containers:
        - name: "release"
          imagePullPolicy: Always
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - init-gcloud-cli
            - semantic-release
