apiVersion: v1
kind: Service
metadata:
  name: needs-retitle
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: needs-retitle
  type: ClusterIP
