apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: needs-retitle
  name: needs-retitle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: needs-retitle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: needs-retitle
    spec:
      containers:
        - args:
            - --dry-run=false
            - --github-endpoint=http://ghproxy
            - --github-endpoint=https://api.github.com
            - --github-token-path=/etc/github/oauth
          image: quay.io/ouzi/needs-retitle:canary
          imagePullPolicy: IfNotPresent
          name: needs-retitle
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/webhook
              name: hmac
              readOnly: true
            - mountPath: /etc/github
              name: oauth
              readOnly: true
            - mountPath: /etc/plugins
              name: plugins
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: hmac
          secret:
            defaultMode: 420
            secretName: hmac-token
        - name: oauth
          secret:
            defaultMode: 420
            secretName: github-token
        - configMap:
            defaultMode: 420
            name: plugins
          name: plugins
